GET http://localhost:3000/prefix/test
###
GET http://localhost:3000/categories
###
GET http://localhost:3000/categories/2
###
POST http://localhost:3000/categories
content-type: application/json
{
    "name": "Leitura"
}
###
PATCH http://localhost:3000/categories/4
Content-Type: application/json
{
    "name": "Material escolar"
}
### 
DELETE http://localhost:3000/categories/4
###
GET http://localhost:3000/products
###
POST http://localhost:3000/products
Content-Type: application/json
{
    "name": "Notebook Dell",
    "description": "Inspiron 3000 Intel Core i5 16GB",
    "price": 3059.1,
    "category_id": 1
}
###
GET http://localhost:3000/products/1/calculateValueInstallments?interest=5&installments=10
