GET http://localhost:3000/prefix/test
###
GET http://localhost:3000/categories
###
GET http://localhost:3000/categories/4
###
POST http://localhost:3000/categories
Content-Type: application/json
{
    "name": "Category test",
    "description:": "Description test"
}
###
PATCH http://localhost:3000/categories
Content-Type: application/json
{
    "name": "Category test",
    "description:": "Description test"
}
### 
DELETE http://localhost:3000/categories/1
