version: '3'
services:
  db:
    image: mysql:8.0.30-debian
    env_file:
      - .env
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_manager