version: '3.5'
services:
  postgres:
    container_name: postgres-product-manager
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-manager
    volumes:
      - ./data:/data/postgres
    ports:
      - "5434:5432"
volumes:
  data: {}